language: node_js
node_js:
  - "12"
branches:
  only:
    - develop
before_install:
  - npm install hexo-cli -g
install:
  - npm install
script:
  # - git submodule init      # 用于更新主题
  # - git submodule update
  - hexo clean
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "wuwb"
  - git config user.email "bin2302@gmail.com"
  - git add .
  - git commit -m "Update blog content by Travis CI"
  - git push --force --quiet "https://${ACCESS_TOKEN}@${GH_REF}" master:master

env:
  global:
    - GH_REF: github.com/wuwb/wuwb.github.io.git

cache:
  directories:
    - node_modules
